name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Package Helm charts
        run: |
          mkdir -p packaged
          helm package ./ --destination packaged

      - name: Generate Helm index
        run: |
          helm repo index packaged --url https:/homelab-blgianini.github.io/helm-templates

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packaged
          publish_branch: gh-pages