name: Package Helm and Set Org Var

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'

jobs:
  package-helm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Package Helm chart
        run: |
            helm package charts/meuchart --destination packaged

      - name: Login no DockerHub Registry (OCI)
        env:
            HELM_REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USER }}
            HELM_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASS }}
        run: |
            echo "$HELM_REGISTRY_PASSWORD" | helm registry login registry-1.docker.io --username "$HELM_REGISTRY_USERNAME" --password-stdin

      - name: Push Helm Chart para DockerHub
        run: |
            CHART_FILE=$(ls packaged/*.tgz)
            helm push "$CHART_FILE" oci://registry-1.docker.io/${{ secrets.DOCKERHUB_USER }}/helm-charts
