name: Publish Helm Chart OCI

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Login no Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          echo $DOCKER_PASSWORD | helm registry login -u $DOCKER_USERNAME --password-stdin docker.io

      - name: Package Helm chart
        run: |
          helm package ./ -d packaged

      - name: Push Helm chart como imagem OCI
        run: |
          CHART_REF="docker.io/${{ secrets.DOCKER_USERNAME }}/helm-chart:0.0.1"
          helm push packaged/helm-template-0.0.1.tgz oci://$CHART_REF
