name: Publish Helm Chart to Docker Registry

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**' # Trigger when changes occur in your chart directory

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.14.0 # Specify your desired Helm version

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Generate version from date
        run: echo "VERSION=0.1.$(date +%s)" >> $GITHUB_ENV

      - name: Package Helm chart
        run: helm package ./ --version $VERSION

      - name: Push Helm chart to registry
        run: helm push my-chart-${{ github.sha }}.tgz oci://docker.io/blgianini/helm-charts