name: Publish Helm Chart to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**' # Ou seu caminho do chart

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Set version
        run: echo "VERSION=0.1.$(date +%s)" >> $GITHUB_ENV

      - name: Package chart
        run: |
          mkdir -p docs
          helm package ./ --version $VERSION -d docs

      - name: Generate Helm index
        run: |
          helm repo index docs --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages