name: Publish Helm Chart to Docker Registry

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Set version
        run: echo "VERSION=0.1.$(date +%s)" >> $GITHUB_ENV

      - name: Package Helm chart
        id: package
        run: |
          FILE=$(helm package ./ --version $VERSION | grep -oP 'Successfully packaged chart and saved it to: \K.*')
          echo "FILE=$FILE" >> $GITHUB_ENV

      - name: Login to OCI registry
        run: helm registry login docker.io -u "${{ secrets.DOCKERHUB_USER }}" --password "${{ secrets.DOCKERHUB_PASS }}"

      - name: Push Helm chart
        run: helm push $FILE oci://docker.io/${{ secrets.DOCKERHUB_USER }}/helm-charts